# This container is specific to the application.
# It contains configuration and data for other containers.
data:
    image: busybox
    container_name: user-bundle_data
    volumes:
        - .:/srv
        - ./docker/.home-developer:/home/developer

console:
    image: meuhmeuhconcept/php-console
    container_name: user-bundle_console
    volumes_from:
        - data
    env_file:
        - ./docker/docker-compose.env
    environment:
        - DNSDOCK_IMAGE=console
    working_dir: /srv
